language: cpp
sudo: required
env: 
  global:
# Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
          - cmake
      #env: COMPILER=g++-7 CC=gcc-7 CXX=g++-7 BOOST_ROOT=/usr/include/boost 
      before_install:
        #- sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
        #- sudo apt-get update
        #- sudo apt-get install g++-7
        - sudo apt-get install libboost-test-dev
        - export CC=/usr/bin/gcc-7
        - export CXX=/usr/bin/g++-7
        - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
        - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
        - gcc -v && g++ -v && cmake --version

script:
  - git submodule update -i --recursive --remote
  - cd model_json_exporter
  - cmake -G "Unix Makefiles" .
  - make
  - make test