language: cpp
sudo: required
env: 
  global:
# Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:
    - os: linux
      dist: trusty
      sudo: required
      env: CC=gcc-7 CXX=g++-7 BOOST_ROOT=/usr/include/boost 
      compiler: gcc
      before_install:
          - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
          - sudo apt-get update
          - sudo apt-get install g++-7
          - sudo apt-get install libboost-dev

script:
  - git submodule update -i --recursive --remote && cd model_json_exporter && cmake -G "Unix Makefiles" . && make && make test